### ISSUE TITLE
Not all USE flags shown on package overview page

### ISSUE THREAD

**Issue by winterqt** [gentoo/soko#15]
`sys-devel/clang` [defines the `default-lld` USE flag](https://github.com/gentoo/gentoo/blob/e4e9110930cb1165c309145b30d60e81b36988dc/sys-devel/clang/metadata.xml#L32), but it does not show up on [its package page](https://packages.gentoo.org/packages/sys-devel/clang).

`sys-devel/clang-common` [defines it in the same way](https://github.com/gentoo/gentoo/blob/e4e9110930cb1165c309145b30d60e81b36988dc/sys-devel/clang-common/metadata.xml#L13), but it does show up on [its package page](https://packages.gentoo.org/packages/sys-devel/clang-common).

The [flag page](https://packages.gentoo.org/useflags/default-lld) itself does show both packages as expected.

This also occurs for some other flags for the same package, such as `default-compiler-rt` and `default-libcxx`.

**Comment by arthurzam** [comment]
Yes, this is indeed an issue. Currently we show useflags, license and maybe more only for first version (what does it mean first - I'm unsure for now - maybe latest, maybe latest not live)

If I'll decide to not show all of them, I should at least mention the versions it matches for (so people know the info isn't precise).
