### ISSUE TITLE
Soko not showing the status of the package version (stable/testing/unavailable) for a given architecture 

### ISSUE THREAD

**Issue by galdutro13** [gentoo/soko#2]
![Captura de Tela-20211020134133-1174x927](https://user-images.githubusercontent.com/71794776/138135515-20c9bf50-e346-41ff-91ad-25fca7b74f3c.png)
![Captura de Tela-20211020134153-1480x907](https://user-images.githubusercontent.com/71794776/138135531-076953e3-a824-4d81-8391-587bd5991313.png)

**Comment by arthurzam** [comment]
This was fixed around last year, can't find exact commit.
In case new package with missing arch status is found, please file a new bug so I would be able to debug and fix it.
Thank you for the report.
