### ISSUE TITLE
[feature request] try to get package longdescription in English too

### ISSUE THREAD

**Issue by xgqt** [gentoo/soko#3]
So package longdescrioption can have a language attribute. 
Maybe soko should try to get both longdescription w/o it as well as the ones with "en" value.

https://github.com/gentoo/soko/blob/8cdad2a374d6115b7fc44d9a415351071ed39c81/pkg/portage/repository/package.go#L86

**Comment by xgqt** [comment]
`grep 'lang="en"' */*/metadata.xml | wc -l`
> 1414

**Comment by arthurzam** [comment]
@xgqt This seems done, but we can't close it because of repo owner issues. Can you please close it?

Current code is:
https://github.com/gentoo/soko/blob/951ff97e8c1f95a512cb120e4948fee305c28c61/pkg/portage/repository/package.go#L85-L89

**Comment by xgqt** [comment]
> @xgqt This seems done, but we can't close it because of repo owner issues. Can you please close it?
> 
> Current code is:
> 
> https://github.com/gentoo/soko/blob/951ff97e8c1f95a512cb120e4948fee305c28c61/pkg/portage/repository/package.go#L85-L89

ok.
